version: '2'

services:

  clickhouse:
    image: yandex/clickhouse-server:18.14
    volumes:
      - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
      - "./data/clickhouse/data:/var/lib/clickhouse/data"
      - "./data/clickhouse/metadata:/var/lib/clickhouse/metadata"

  clickhouse-init:
    image: yandex/clickhouse-server:18.14
    volumes:
      - "./init.sql:/init.sql"
    entrypoint: |
      bash -c '
        sleep 5
        export HOME=/var/lib/clickhouse/
        cat /init.sql | clickhouse client --host clickhouse --multiquery'
    links:
      - clickhouse

  carbon-clickhouse:
    image: lomik/carbon-clickhouse:v0.9.1
    volumes:
      - "./data/carbon-clickhouse:/data/carbon-clickhouse"
      - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
    ports:
      - "2003:2003" # plain tcp
      - "2003:2003/udp" # plain udp
      - "2004:2004" # pickle
      - "2006:2006" # prometheus remote write
    links:
      - clickhouse
    depends_on:
      - clickhouse-init

  graphite-clickhouse:
    image: lomik/graphite-clickhouse:v0.8.1
    volumes:
      - "./rollup.xml:/etc/graphite-clickhouse/rollup.xml"
      - "./graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf"
    links:
      - clickhouse

  graphite-web:
    image: graphiteapp/graphite-statsd:1.1.4-10
    volumes:
      - "./graphiteweb_entrypoint.sh:/entrypoint.sh"
      - "./graphiteweb.conf:/opt/graphite/webapp/graphite/local_settings.py"
    entrypoint: /entrypoint.sh
    links:
      - graphite-clickhouse
    ports:
      - "80:80" # http ui

  haggar:
    image: haggar:latest
    build: ./haggar
    depends_on:
      - clickhouse
      - carbon-clickhouse
    command: sh -c "sleep 60 && ./haggar -agents=10 -metrics=1000 -carbon=carbon-clickhouse:2003"
